# name: Build All

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-mac:
    name: Build for Mac OSX
    runs-on: macos-latest
    strategy:
      fail-fast: false
    
    steps:
    - name: Install SDL
      uses: libsdl-org/setup-sdl@main
      id: sdl
      with:
        install-linux-dependencies: false
        version: 3-head

    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Prepare Upload
      run: |
        mkdir ./upload/
        cp $SDL3_ROOT/lib/* ./upload/
        cp ${{ steps.strings.outputs.build-output-dir }}/app ./upload/

    - name: Upload Artifact
      if: matrix.os != 'windows-latest'
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Mac-build
        path: ./upload/*

